services:
    ### MySQL Container
    mysql:
        build: ./db/.
        healthcheck:
            test: mysqladmin ping -h localhost -p1234
            interval: 10s
            timeout: 3s
            retries: 100
            start_period: 0s
        image: camilaolim/p2_db:latest

    node:
        depends_on:
            mysql: 
                condition: service_healthy

        build: ./src/.
        env_file: ./src/.env
        ports:
            - "8080:8080"
        command: npm run start
        restart: on-failure
        environment:
            DB_HOST: mysql
        image: camilaolim/p2_node:latest
#         networks:
#           - internalnet


# networks:
#     internalnet:
#         driver: bridge
